### ISSUE TITLE
コードの表示について

### ISSUE THREAD

**Issue by kaorun55** [HoloMagicians/HolographicAcademyJP#3]
ソースは埋め込みますか？
埋め込む場合はコメントも日本語化しますか？
訳文： https://github.com/kaorun55/HolographicAcademyJP/blob/master/Contents/holograms_101.md#手順-1
原文： https://developer.microsoft.com/en-us/windows/mixed-reality/holograms_101

**Comment by takkanao** [comment]
確かに .cs 開かないですね。そもそも。。。

**Comment by takkanao** [comment]
あー、状況理解しました。ソースからコピッて対応いただけるなら、「訳文」のほうで対応していただいた表現方法でお願いできるとありがたいですm(_ _)m 気付いてなかったので、とても助かりました！

**Comment by kaorun55** [comment]
こちらも了解ですー

**Comment by kaorun55** [comment]
@takkanao 
コメントの日本語化どうしますか？

**Comment by takkanao** [comment]
@kaorun55 訳さなくていいと思いますが、如何でしょうか？

**Comment by kaorun55** [comment]
どちらでもいいと思います。
では、そのままで
